#!/bin/bash

branch_name=$(git symbolic-ref --short HEAD)
branch_pattern="(admin|test|application|operation|framework|hotfix)/[a-z]+[a-z-]*" 
echo $branch_name | egrep -x "$branch_pattern" > /dev/null

if [ $? == 1 ]; then
    echo "ERROR: $branch_name does not match the branch naming scheme"
    echo "To rename the current branch run \"git branch -m new_branch_name\", for further instructions see the README on the github page"
    exit 1
fi

exit 0
