/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4 */

#include <RFileTransfer.pb.h>
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(file_transfer_message, file_transfer_message, AUTO)


PB_BIND(obc_telemetry, obc_telemetry, AUTO)


PB_BIND(receiver_telemetry, receiver_telemetry, AUTO)


PB_BIND(transmitter_telemetry, transmitter_telemetry, AUTO)


PB_BIND(transceiver_telemetry, transceiver_telemetry, AUTO)


PB_BIND(camera_power_telemetry, camera_power_telemetry, AUTO)


PB_BIND(camera_configuration_telemetry, camera_configuration_telemetry, AUTO)


PB_BIND(camera_telemetry, camera_telemetry, AUTO)


PB_BIND(sun_sensor_data, sun_sensor_data, AUTO)


PB_BIND(eps_telemetry, eps_telemetry, AUTO)


PB_BIND(battery_telemetry, battery_telemetry, AUTO)


PB_BIND(antenna_side_data, antenna_side_data, AUTO)


PB_BIND(antenna_telemetry, antenna_telemetry, AUTO)


PB_BIND(dosimeter_board_data, dosimeter_board_data, AUTO)


PB_BIND(dosimeter_data, dosimeter_data, AUTO)


PB_BIND(image_packet, image_packet, AUTO)


PB_BIND(module_error_report, module_error_report, AUTO)


PB_BIND(component_error_report, component_error_report, AUTO)


PB_BIND(error_record, error_record, AUTO)


PB_BIND(error_report_summary, error_report_summary, AUTO)




