/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4 */

#include <RFileTransfer.pb.h>
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(FileTransferMessage, FileTransferMessage, AUTO)


PB_BIND(ObcTelemetry, ObcTelemetry, AUTO)


PB_BIND(TransceiverTelemetry, TransceiverTelemetry, AUTO)


PB_BIND(TransceiverTelemetry_receiverTelemetry, TransceiverTelemetry_receiverTelemetry, AUTO)


PB_BIND(TransceiverTelemetry_transmitterTelemetry, TransceiverTelemetry_transmitterTelemetry, AUTO)


PB_BIND(CameraTelemetry, CameraTelemetry, AUTO)


PB_BIND(EpsTelemetry, EpsTelemetry, AUTO)


PB_BIND(BatteryTelemetry, BatteryTelemetry, AUTO)


PB_BIND(AntennaTelemetry, AntennaTelemetry, AUTO)


PB_BIND(DosimeterData, DosimeterData, AUTO)


PB_BIND(DosimeterData_DosimeterBoardData, DosimeterData_DosimeterBoardData, AUTO)


PB_BIND(ImagePacket, ImagePacket, AUTO)




