/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4 */

#include <RProtocol.pb.h>
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(protocol_message, protocol_message, AUTO)


PB_BIND(ack, ack, AUTO)


PB_BIND(nack, nack, AUTO)



