/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4 */

#include <RProtocol.pb.h>
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ProtocolMessage, ProtocolMessage, AUTO)


PB_BIND(Ack, Ack, AUTO)


PB_BIND(Nack, Nack, AUTO)



