/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.4 */

#ifndef PB_RRADSAT_PB_H_INCLUDED
#define PB_RRADSAT_PB_H_INCLUDED
#include <pb.h>
#include <RProtocol.pb.h>
#include <RTelecommands.pb.h>
#include <RFileTransfer.pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _RadsatMessage {
    pb_size_t which_service;
    union {
        ProtocolMessage protocolMessage;
        FileTransferMessage fileTransferMessage;
        TelecommandMessage telecommandMessage;
    };
} RadsatMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define RadsatMessage_init_default               {0, {ProtocolMessage_init_default}}
#define RadsatMessage_init_zero                  {0, {ProtocolMessage_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define RadsatMessage_protocolMessage_tag        1
#define RadsatMessage_fileTransferMessage_tag    2
#define RadsatMessage_telecommandMessage_tag     3

/* Struct field encoding specification for nanopb */
#define RadsatMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (service,protocolMessage,protocolMessage),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (service,fileTransferMessage,fileTransferMessage),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (service,telecommandMessage,telecommandMessage),   3)
#define RadsatMessage_CALLBACK NULL
#define RadsatMessage_DEFAULT NULL
#define RadsatMessage_service_protocolMessage_MSGTYPE ProtocolMessage
#define RadsatMessage_service_fileTransferMessage_MSGTYPE FileTransferMessage
#define RadsatMessage_service_telecommandMessage_MSGTYPE TelecommandMessage

extern const pb_msgdesc_t RadsatMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define RadsatMessage_fields &RadsatMessage_msg

/* Maximum encoded size of messages (where known) */
#define RadsatMessage_size                       217

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
