/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4 */

#include <RTelecommands.pb.h>
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(telecommand_message, telecommand_message, AUTO)


PB_BIND(begin_pass, begin_pass, AUTO)


PB_BIND(begin_file_transfer, begin_file_transfer, AUTO)


PB_BIND(cease_transmission, cease_transmission, AUTO)


PB_BIND(resume_transmission, resume_transmission, AUTO)


PB_BIND(update_time, update_time, AUTO)


PB_BIND(reset, reset, AUTO)




