/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4 */

#include <RTelecommands.pb.h>
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(TelecommandMessage, TelecommandMessage, AUTO)


PB_BIND(TelecommandResponse, TelecommandResponse, AUTO)


PB_BIND(TelecommandBegin, TelecommandBegin, AUTO)


PB_BIND(CeaseTransmission, CeaseTransmission, AUTO)


PB_BIND(UpdatePassTime, UpdatePassTime, AUTO)



