/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.4 */

#ifndef PB_RTELECOMMANDS_PB_H_INCLUDED
#define PB_RTELECOMMANDS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _CeaseTransmission {
    char dummy_field;
} CeaseTransmission;

typedef struct _TelecommandBegin {
    char dummy_field;
} TelecommandBegin;

typedef struct _TelecommandResponse {
    int32_t response;
} TelecommandResponse;

typedef struct _UpdatePassTime {
    int32_t unixTime;
} UpdatePassTime;

typedef struct _TelecommandMessage {
    pb_size_t which_message;
    union {
        CeaseTransmission ceaseTransmission;
        UpdatePassTime updatePassTime;
    };
} TelecommandMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define TelecommandMessage_init_default          {0, {CeaseTransmission_init_default}}
#define TelecommandResponse_init_default         {0}
#define TelecommandBegin_init_default            {0}
#define CeaseTransmission_init_default           {0}
#define UpdatePassTime_init_default              {0}
#define TelecommandMessage_init_zero             {0, {CeaseTransmission_init_zero}}
#define TelecommandResponse_init_zero            {0}
#define TelecommandBegin_init_zero               {0}
#define CeaseTransmission_init_zero              {0}
#define UpdatePassTime_init_zero                 {0}

/* Field tags (for use in manual encoding/decoding) */
#define TelecommandResponse_response_tag         1
#define UpdatePassTime_unixTime_tag              1
#define TelecommandMessage_ceaseTransmission_tag 1
#define TelecommandMessage_updatePassTime_tag    2

/* Struct field encoding specification for nanopb */
#define TelecommandMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,ceaseTransmission,ceaseTransmission),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,updatePassTime,updatePassTime),   2)
#define TelecommandMessage_CALLBACK NULL
#define TelecommandMessage_DEFAULT NULL
#define TelecommandMessage_message_ceaseTransmission_MSGTYPE CeaseTransmission
#define TelecommandMessage_message_updatePassTime_MSGTYPE UpdatePassTime

#define TelecommandResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    response,          1)
#define TelecommandResponse_CALLBACK NULL
#define TelecommandResponse_DEFAULT NULL

#define TelecommandBegin_FIELDLIST(X, a) \

#define TelecommandBegin_CALLBACK NULL
#define TelecommandBegin_DEFAULT NULL

#define CeaseTransmission_FIELDLIST(X, a) \

#define CeaseTransmission_CALLBACK NULL
#define CeaseTransmission_DEFAULT NULL

#define UpdatePassTime_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    unixTime,          1)
#define UpdatePassTime_CALLBACK NULL
#define UpdatePassTime_DEFAULT NULL

extern const pb_msgdesc_t TelecommandMessage_msg;
extern const pb_msgdesc_t TelecommandResponse_msg;
extern const pb_msgdesc_t TelecommandBegin_msg;
extern const pb_msgdesc_t CeaseTransmission_msg;
extern const pb_msgdesc_t UpdatePassTime_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define TelecommandMessage_fields &TelecommandMessage_msg
#define TelecommandResponse_fields &TelecommandResponse_msg
#define TelecommandBegin_fields &TelecommandBegin_msg
#define CeaseTransmission_fields &CeaseTransmission_msg
#define UpdatePassTime_fields &UpdatePassTime_msg

/* Maximum encoded size of messages (where known) */
#define TelecommandMessage_size                  13
#define TelecommandResponse_size                 11
#define TelecommandBegin_size                    0
#define CeaseTransmission_size                   0
#define UpdatePassTime_size                      11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
