/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4 */

#include <RTelecommands.pb.h>
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(TelecommandMessage, TelecommandMessage, AUTO)


PB_BIND(BeginPass, BeginPass, AUTO)


PB_BIND(BeginFileTransfer, BeginFileTransfer, AUTO)


PB_BIND(CeaseTransmission, CeaseTransmission, AUTO)


PB_BIND(ResumeTransmission, ResumeTransmission, AUTO)


PB_BIND(UpdateTime, UpdateTime, AUTO)


PB_BIND(Reset, Reset, AUTO)




