/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.4 */

#ifndef PB_RTELECOMMANDS_PB_H_INCLUDED
#define PB_RTELECOMMANDS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _reset_device_t {
    reset_device_t_Obc = 0,
    reset_device_t_Transmitter = 1,
    reset_device_t_Receiver = 2,
    reset_device_t_AntennaSideA = 3,
    reset_device_t_AntennaSideB = 4
} reset_device_t;

/* Struct definitions */
typedef struct _begin_file_transfer {
    char dummy_field;
} begin_file_transfer;

typedef struct _resume_transmission {
    char dummy_field;
} resume_transmission;

typedef struct _begin_pass {
    uint32_t PassLength;
} begin_pass;

typedef struct _cease_transmission {
    uint32_t Duration;
} cease_transmission;

typedef struct _reset {
    reset_device_t Device;
    uint32_t Hard;
} reset;

typedef struct _update_time {
    uint32_t UnixTime;
} update_time;

typedef struct _telecommand_message {
    pb_size_t which_message;
    union {
        begin_pass BeginPass;
        begin_file_transfer BeginFileTransfer;
        cease_transmission CeaseTransmission;
        resume_transmission ResumeTransmission;
        update_time UpdateTime;
        reset Reset;
    };
} telecommand_message;


/* Helper constants for enums */
#define _reset_device_t_MIN reset_device_t_Obc
#define _reset_device_t_MAX reset_device_t_AntennaSideB
#define _reset_device_t_ARRAYSIZE ((reset_device_t)(reset_device_t_AntennaSideB+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define telecommand_message_init_default         {0, {begin_pass_init_default}}
#define begin_pass_init_default                  {0}
#define begin_file_transfer_init_default         {0}
#define cease_transmission_init_default          {0}
#define resume_transmission_init_default         {0}
#define update_time_init_default                 {0}
#define reset_init_default                       {_reset_device_t_MIN, 0}
#define telecommand_message_init_zero            {0, {begin_pass_init_zero}}
#define begin_pass_init_zero                     {0}
#define begin_file_transfer_init_zero            {0}
#define cease_transmission_init_zero             {0}
#define resume_transmission_init_zero            {0}
#define update_time_init_zero                    {0}
#define reset_init_zero                          {_reset_device_t_MIN, 0}

/* Field tags (for use in manual encoding/decoding) */
#define begin_pass_PassLength_tag                1
#define cease_transmission_Duration_tag          1
#define reset_Device_tag                         1
#define reset_Hard_tag                           2
#define update_time_UnixTime_tag                 1
#define telecommand_message_BeginPass_tag        1
#define telecommand_message_BeginFileTransfer_tag 2
#define telecommand_message_CeaseTransmission_tag 3
#define telecommand_message_ResumeTransmission_tag 4
#define telecommand_message_UpdateTime_tag       5
#define telecommand_message_Reset_tag            6

/* Struct field encoding specification for nanopb */
#define telecommand_message_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,BeginPass,BeginPass),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,BeginFileTransfer,BeginFileTransfer),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,CeaseTransmission,CeaseTransmission),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,ResumeTransmission,ResumeTransmission),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,UpdateTime,UpdateTime),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,Reset,Reset),   6)
#define telecommand_message_CALLBACK NULL
#define telecommand_message_DEFAULT NULL
#define telecommand_message_message_BeginPass_MSGTYPE begin_pass
#define telecommand_message_message_BeginFileTransfer_MSGTYPE begin_file_transfer
#define telecommand_message_message_CeaseTransmission_MSGTYPE cease_transmission
#define telecommand_message_message_ResumeTransmission_MSGTYPE resume_transmission
#define telecommand_message_message_UpdateTime_MSGTYPE update_time
#define telecommand_message_message_Reset_MSGTYPE reset

#define begin_pass_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   PassLength,        1)
#define begin_pass_CALLBACK NULL
#define begin_pass_DEFAULT NULL

#define begin_file_transfer_FIELDLIST(X, a) \

#define begin_file_transfer_CALLBACK NULL
#define begin_file_transfer_DEFAULT NULL

#define cease_transmission_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   Duration,          1)
#define cease_transmission_CALLBACK NULL
#define cease_transmission_DEFAULT NULL

#define resume_transmission_FIELDLIST(X, a) \

#define resume_transmission_CALLBACK NULL
#define resume_transmission_DEFAULT NULL

#define update_time_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   UnixTime,          1)
#define update_time_CALLBACK NULL
#define update_time_DEFAULT NULL

#define reset_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    Device,            1) \
X(a, STATIC,   SINGULAR, UINT32,   Hard,              2)
#define reset_CALLBACK NULL
#define reset_DEFAULT NULL

extern const pb_msgdesc_t telecommand_message_msg;
extern const pb_msgdesc_t begin_pass_msg;
extern const pb_msgdesc_t begin_file_transfer_msg;
extern const pb_msgdesc_t cease_transmission_msg;
extern const pb_msgdesc_t resume_transmission_msg;
extern const pb_msgdesc_t update_time_msg;
extern const pb_msgdesc_t reset_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define telecommand_message_fields &telecommand_message_msg
#define begin_pass_fields &begin_pass_msg
#define begin_file_transfer_fields &begin_file_transfer_msg
#define cease_transmission_fields &cease_transmission_msg
#define resume_transmission_fields &resume_transmission_msg
#define update_time_fields &update_time_msg
#define reset_fields &reset_msg

/* Maximum encoded size of messages (where known) */
#define telecommand_message_size                 10
#define begin_pass_size                          6
#define begin_file_transfer_size                 0
#define cease_transmission_size                  6
#define resume_transmission_size                 0
#define update_time_size                         6
#define reset_size                               8

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
