/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4 */

#include <fileTransfer.pb.h>
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(fileTransferMessage, fileTransferMessage, AUTO)


PB_BIND(fileTransferResponse, fileTransferResponse, AUTO)


PB_BIND(fileTransferPacket, fileTransferPacket, AUTO)



