/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4 */

#include <fileTransfer.pb.h>
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(FileTransferMessage, FileTransferMessage, AUTO)


PB_BIND(FileTransferResponse, FileTransferResponse, AUTO)


PB_BIND(FileTransferPacket, FileTransferPacket, AUTO)



